### ISSUE TITLE
I Can't Use Any Of The 1.10 Versions Because Of 'Invalid Plugin.yml'.

### ISSUE THREAD

**Issue by IAmBabyGroot** [hsyyid/CommandSigns#14]
![invalid plugin yml](https://cloud.githubusercontent.com/assets/17186798/21233619/baf95b44-c2e7-11e6-8fda-d2b4793e2e18.jpg)

I Am Using Craftbukkit 1.10.2.

**Comment by hsyyid** [comment]
This is a Sponge plugin.
