### ISSUE TITLE
After Placing down sign reading [CommandSign] on the first line and using /setcommand give @p Diamond Right clicking on the sign does nothing

### ISSUE THREAD

**Issue by AuraTheBatPone** [hsyyid/CommandSigns#2]
Title says it all and yes i tried it without the /

**Comment by hsyyid** [comment]
Okay, I'll check it.

**Comment by hsyyid** [comment]
Found the problem. It seems to be a bug with Sponge. Please try using an older Sponge version, such as 596 or higher.

**Comment by AuraTheBatPone** [comment]
don't you mean 596 or lower? :P

**Comment by AuraTheBatPone** [comment]
also i can't find 596 i could only find 592 and that didn't work it just crashed whenever i put a plugin in

**Comment by hsyyid** [comment]
@SilentDeathTheSeal it was a bug with Sponge. blood has fixed it, and it should be fixed in the latest Sponge. Thanks for notifying me of this issue. :smile:
