### ISSUE TITLE
sqlite error

### ISSUE THREAD

**Issue by seema84** [hsyyid/CommandSigns#3]
Sponge Vanilla 3.0.0

[STDERR]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table:
 COMMANDSIGNS)
[STDERR]:      at org.sqlite.core.DB.newSQLException(DB.java:890)
[STDERR]:      at org.sqlite.core.DB.newSQLException(DB.java:901)
[STDERR]:      at org.sqlite.core.DB.throwex(DB.java:868)
[STDERR]:      at org.sqlite.core.NativeDB.prepare(Native Method)
[STDERR]:      at org.sqlite.core.DB.prepare(DB.java:211)
[STDERR]:      at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81)
[STDERR]:      at io.github.hsyyid.commandsigns.utils.DatabaseManager.readCommandSigns(Databa
seManager.java:107)
[STDERR]:      at io.github.hsyyid.commandsigns.CommandSigns.onServerStart(CommandSigns.java:
139)
[STDERR]:      at org.spongepowered.common.event.listener.GameStartingServerEventListener_Com
mandSigns_onServerStart10.handle(Unknown Source)
[STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener
.java:86)
[STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:247)
[STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:258)
[STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:262)
[STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:162)
[STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.callServerStarting(SourceFil
e:82)
[STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:210)

[STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:417)
[STDERR]:      at java.lang.Thread.run(Unknown Source)

**Comment by hsyyid** [comment]
This error will only happen once, on first install. I'll fix it soon.

**Comment by seema84** [comment]
ok thanks
