### ISSUE TITLE
Why use a database?

### ISSUE THREAD

**Issue by meyerzinn** [hsyyid/CommandSigns#4]
Why does CommandSigns use a database rather than the Data API for persistently storing data about a sign?

**Comment by hsyyid** [comment]
CommandSigns was made before the Data API system was implemented for plugins, so it has not been updated to use it yet, when I find time, it will be.

**Comment by hsyyid** [comment]
Finished in 31414e60d1038917860fbc4adde93d4d9cd3cc84
