### ISSUE TITLE
Commandsign 1.3 for api5-1.10.2 error in spongeforge-api5-2092-1746

### ISSUE THREAD

**Issue by comdarksider** [hsyyid/CommandSigns#7]
commandsign 1.3 for API5-1.10.2 
error in spongeforge-API5.0-1.10.2-2092-1746
UE is error. UC is normal

Dear. HassanS6000 please update plugin.
Thank you very much.

Full error code latest : http://pastebin.com/agDbNugs1

**Comment by sleiss** [comment]
I've updated the project to SpongeAPI 6.0.0. 
See https://github.com/hsyyid/CommandSigns/pull/9.
