### ISSUE TITLE
commandsign 1.3 for api5 is not compatible spongeforge latest vesion.

### ISSUE THREAD

**Issue by comdarksider** [hsyyid/CommandSigns#8]
I test on tue 24 september 2016 20:07 PM.
commandsign 1.3 for api5 is not compatible spongeforge latest vesion.

commandsign 1.3 for API5-1.10.2 
error in spongeforge-API5.0-1.10.2-2092-1753
UE is error. UC is normal

Dear. HassanS6000 please update plugin.
Thank you very much.

Full error code latest : http://pastebin.com/WyK2i8qZ

**Comment by sleiss** [comment]
I've updated the project to SpongeAPI 6.0.0. 
See https://github.com/hsyyid/CommandSigns/pull/9.

**Comment by comdarksider** [comment]
No download for API6.0

**Comment by comdarksider** [comment]
do hot have download link for api6.0 wait hassans6000.
